### ISSUE TITLE
T-Rex entity spams console with "Can't Render Texture" in 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [JurassiCraftTeam/JurassiCraft2#143]
I get error messages about the T-Rex in my console like this whenever I spawn in a T-Rex:

`[16:10:22] [Client thread/ERROR]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101) ~[bza.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) ~[bza.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(Render.java:146) ~[bus.class:?]
	at net.minecraft.client.renderer.entity.Render.func_180548_c(Render.java:139) ~[bus.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:293) ~[bvl.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:220) [bvl.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50) [bvq.class:?]
	at org.jurassicraft.client.render.entity.DinosaurRenderer.doRender(DinosaurRenderer.java:71) [DinosaurRenderer.class:?]
	at org.jurassicraft.client.render.entity.DinosaurRenderer.func_76986_a(DinosaurRenderer.java:20) [DinosaurRenderer.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.redirect$onRenderEntity$zzh000(RenderManager.java:683) [bur.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415) [bur.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392) [bur.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:810) [bqm.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1359) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.OutOfMemoryError: Java heap space`

I also end up getting a HUGE lag spike to the point I have to close the game. I have JurassiCraft 2.0.5 with LLibrary 1.7.4 both for 1.11.2

**Comment by Gamebrothers4** [comment]
Upgrade your java heap space

**Comment by twoninefour** [comment]
Java ran out of memory. Nothing we could do be downgrade the textures

**Comment by gegy1000** [comment]
You can allocate more RAM to your game through the VM arguments.
