### ISSUE TITLE
2.1 is Crashing (screen render)

### ISSUE THREAD

**Issue by tpayne0322** [JurassiCraftTeam/JurassiCraft2#215]
So I've checked this is a problem with my jc 2.1
whenever i try to load 2.1 on my mac it crashes and on the crash it says its because of a rendering issue. 
Here's the report, anything helps. (it only crashes when 2.1 is in)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.0-1.10.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 13/10/17 3:27 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (277, 239). Absolute: (555, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 135016088 bytes (128 MB) / 386334720 bytes (368 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	U	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	U	Bullseye{1.0.3} [Bullseye] (Bullseye-Mod-1.10.2.jar) 
	U	customnpcs{1.9.0_beta} [CustomNPCs] (CustomNPCs_1.10.2_beta(10oct16).jar) 
	U	DragonMounts{r46-1.10.2} [Dragon Mounts] (Dragon-Mounts-Mod-1.10.2.jar) 
	U	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	U	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.106.jar) 
	U	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.106.jar) 
	U	godweapons{4.5_1.10.2} [Gods' Weapons] (Gods-Weapons-Mod-1.10.2.jar) 
	U	journeymap{1.10.2-5.4.7} [JourneyMap] (journeymap-1.10.2-5.4.7.jar) 
	U	jurassicraft{2.1.0-dev} [JurassiCraft] (JurassiCraft-2.1.0.jar) 
	U	llibrary{1.7.0} [LLibrary] (llibrary-1.7.0-1.10.2.jar) 
	U	sgcraft{1.13.2} [SG Craft] (SGCraft-1.13.2-mc1.10.2.jar) 
	U	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.0-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2239
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-10.14.73, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

**Comment by gegy1000** [comment]
Try update Forge (and also JC) This is not a problem with JC.

**Comment by tpayne0322** [comment]
Oh ok. Thank you.

**Comment by tpayne0322** [comment]
Thank you! I updated my Forge and Library.
RESPECT FOR YOU BRO
