### ISSUE TITLE
Crash when birth wand used in 1.11.2

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#282]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PLCore (JurassiCraft-1.11.2-2.1.4.jar)
  llibrary (llibrary-1.7.11-1.11.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/10/18 1:23 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:704)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:949)
	at org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity.func_70071_h_(BrachiosaurusEntity.java:28)
	at net.minecraft.world.World.func_72866_a(World.java:1968)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:704)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:949)
	at org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity.func_70071_h_(BrachiosaurusEntity.java:28)
	at net.minecraft.world.World.func_72866_a(World.java:1968)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.brachiosaurus (org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity)
	Entity ID: 5460
	Entity Name: entity.brachiosaurus.name
	Entity's Exact location: 40.70, 63.00, -2.22
	Entity's Block location: World: (40,63,-3), Chunk: (at 8,3,13 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.01, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['StarDinoBoy'/1118, l='New World', x=37.40, y=63.00, z=0.36]]
	Chunk stats: ServerChunkCache: 652 Drop: 0
	Level seed: 2955431935278402169
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 711 game time, 711 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 42407 (now: false), thunder time: 87198 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 761521280 bytes (726 MB) / 1531445248 bytes (1460 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.38 Powered by Forge 13.20.1.2588 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2588.jar) 
	UCHIJAAAA	forge{13.20.1.2588} [Minecraft Forge] (forge-1.11.2-13.20.1.2588.jar) 
	UCHIJAAAA	llibrary{1.7.11} [LLibrary] (llibrary-1.7.11-1.11.2.jar) 
	UCHIJAAAA	jurassicraft{2.1.4} [JurassiCraft] (JurassiCraft-1.11.2-2.1.4.jar) 
	Loaded coremods (and transformers): 
PLCore (JurassiCraft-1.11.2-2.1.4.jar)
  org.jurassicraft.server.pl.PLTransformer
llibrary (llibrary-1.7.11-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['StarDinoBoy'/1118, l='New World', x=37.40, y=63.00, z=0.36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Wyn-Price** [comment]
Try the latest verion on curseforge [here](https://minecraft.curseforge.com/projects/jurassicraft2/files/2571215)
