### ISSUE TITLE
Incompatibility with LLibrary

### ISSUE THREAD

**Issue by oooooof74** [JurassiCraftTeam/JurassiCraft2#287]
No matter the version of LLibrary installed, always says that it is 1.7.7 requesting 1.7.9+

I've tried the 3 most recent updates of the mod with the same result each time.

[15:48:07] [main/INFO] [FML]: Forge Mod Loader has identified 17 mods to load
[15:48:08] [main/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jurassicraft (JurassiCraft) requires [llibrary@[1.7.9,)]
[15:48:08] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod jurassicraft (JurassiCraft) requires [llibrary@[1.7.9,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:48:08] [main/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.

**Comment by BrownBoiiWonder** [comment]
What version of llib do you have installed(a screenshot of your mods folder would be helpful)

**Comment by oooooof74** [comment]
My mod folder is filled with random stuff (All sorts of little tweakers), but I tried the 3 most recent versions. 1.12.2, 1.12.1 and the release 1.12

**Comment by Wyn-Price** [comment]
You hadn't get LLibrary 1.7.9. post the whole latest.log ?

**Comment by BrownBoiiWonder** [comment]
And you shouldn't be using anything other than the 1.12.2 version of llib

**Comment by oooooof74** [comment]
[15:47:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:50] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2707 for Minecraft 1.12.2 loading
[15:47:50] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_74, running on Mac OS X:x86_64:10.10.5, installed at /Users/moon/Desktop/Minecraft.app/Contents/runtime/jre-x64/1.8.0_74
[15:47:50] [main/INFO] [FML]: Searching /Users/moon/Library/Application Support/minecraft/mods for mods
[15:47:50] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[15:47:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LLibrary-1.12.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:47:50] [main/ERROR] [FML]: The coremod net.ilexiconn.llibrary.server.core.plugin.LLibraryPlugin is requesting minecraft version 1.12.1 and minecraft is 1.12.2. It will be ignored.
[15:47:50] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_D1.jar
[15:47:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:47:50] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:47:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:50] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:47:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:47:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:47:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[15:47:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: /Users/moon/Library/Application Support/minecraft/mods/OptiFine_1.12.2_HD_U_D1.jar
[15:47:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:53] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:47:53] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:47:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:53] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[15:47:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:47:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:54] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:47:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:47:54] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[15:47:54] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:47:54] [main/INFO] [BetterFps]: Patching net.minecraft.client.Minecraft... (bib)
[15:47:55] [main/INFO] [BetterFps]: Patching net.minecraft.client.entity.EntityPlayerSP... (bud)
[15:47:56] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: InASuit
[15:47:56] [main/INFO] [BetterFps]: Patching net.minecraft.block.Block... (aow)
[15:47:57] [main/INFO] [BetterFps]: Patching math utils with "RIVENS_HALF" algorithm
[15:47:59] [main/INFO] [BetterFps]: Patching net.minecraft.tileentity.TileEntityBeacon... (avh)
[15:47:59] [main/INFO] [BetterFps]: Patching net.minecraft.block.BlockHopper... (arl)
[15:47:59] [main/INFO] [BetterFps]: Patching net.minecraft.tileentity.TileEntityHopper... (avw)
[15:48:03] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[15:48:03] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[15:48:03] [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
[15:48:03] [main/INFO] [BetterFps]: Patching net.minecraft.client.renderer.EntityRenderer... (buq)
[15:48:04] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[15:48:04] [main/INFO] [BetterFps]: Patching net.minecraft.client.gui.GuiOptions... (ble)
[15:48:04] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[15:48:05] [main/INFO] [Config]: [OptiFine] 
[15:48:05] [main/INFO] [Config]: [OptiFine] OptiFine_1.12.2_HD_U_D1
[15:48:05] [main/INFO] [Config]: [OptiFine] Build: 20180323-135452
[15:48:05] [main/INFO] [Config]: [OptiFine] OS: Mac OS X (x86_64) version 10.10.5
[15:48:05] [main/INFO] [Config]: [OptiFine] Java: 1.8.0_74, Oracle Corporation
[15:48:05] [main/INFO] [Config]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[15:48:05] [main/INFO] [Config]: [OptiFine] LWJGL: 2.9.4
[15:48:05] [main/INFO] [Config]: [OptiFine] OpenGL: NVIDIA GeForce 9400 OpenGL Engine, version 2.1 NVIDIA-10.0.35 310.90.10.05b12
, NVIDIA Corporation
[15:48:05] [main/INFO] [Config]: [OptiFine] OpenGL Version: 2.1.0
[15:48:05] [main/INFO] [Config]: [OptiFine] Maximum texture size: 8192x8192
[15:48:05] [Thread-3/INFO] [Config]: [OptiFine] Checking for new version
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] ShadersMod version: 2.4.12
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] OpenGL Version: 2.1 NVIDIA-10.0.35 310.90.10.05b12
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] Vendor:  NVIDIA Corporation
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] Renderer: NVIDIA GeForce 9400 OpenGL Engine
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] Load ShadersMod configuration.
[15:48:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] No shaderpack loaded.
[15:48:05] [main/INFO] [Config]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded
[15:48:05] [main/INFO] [Config]: [OptiFine] VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
[15:48:05] [Thread-3/INFO] [Config]: [OptiFine] Version found: D1
[15:48:05] [main/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_D1, enabling compatibility features
[15:48:05] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2948444296 bytes (2811 MB) / 3221225472 bytes (3072 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.0.35 310.90.10.05b12
' Renderer: 'NVIDIA GeForce 9400 OpenGL Engine'
[15:48:05] [main/INFO] [FML]: MinecraftForge v14.23.4.2707 Initialized
[15:48:05] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[15:48:05] [main/INFO] [FML]: Replaced 1036 ore ingredients
[15:48:06] [main/INFO] [FML]: Searching /Users/moon/Library/Application Support/minecraft/mods for mods
[15:48:07] [main/WARN] [FML]: Mod ironchest is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-7.0.40.824
[15:48:07] [Thread-4/INFO] [FML]: Using sync timing. 200 frames of Display.update took 790892157 nanos
[15:48:07] [main/INFO] [FML]: Forge Mod Loader has identified 17 mods to load
[15:48:08] [main/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jurassicraft (JurassiCraft) requires [llibrary@[1.7.9,)]
[15:48:08] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod jurassicraft (JurassiCraft) requires [llibrary@[1.7.9,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:48:08] [main/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[15:48:08] [main/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Ambience, FMLFileResourcePack:Bear With Me, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JurassiCraft, FMLFileResourcePack:LLibrary, FMLFileResourcePack:The Lost Cities, FMLFileResourcePack:Primitive Mobs, FMLFileResourcePack:Resource Loader, FMLFileResourcePack:Weapon Levels, CustomResources, f81517ca516363c381528480bb4c5189-New Default Betapack V2, Extra 3D weapons if you get an anvil and rename a weapon., RIOTCRAFT TEXTURE PACK, CustomOverridingResources
[15:48:08] [main/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[15:48:08] [main/INFO] [Config]: [OptiFine] *** Reloading textures ***
[15:48:08] [main/INFO] [Config]: [OptiFine] Resource packs: f81517ca516363c381528480bb4c5189-New Default Betapack V2, Extra 3D weapons if you get an anvil and rename a weapon., RIOTCRAFT TEXTURE PACK
[15:48:10] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[15:48:11] [main/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[15:48:11] [main/ERROR] [net.minecraft.client.Minecraft]: @ Pre startup
[15:48:11] [main/ERROR] [net.minecraft.client.Minecraft]: 1281: Invalid value
[15:48:11] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[15:48:11] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:48:11] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[15:48:11] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[15:48:12] [main/INFO] [Config]: [OptiFine] *** Reloading custom textures ***
[15:53:18] [main/INFO] [net.minecraft.client.Minecraft]: Stopping!
[15:53:18] [main/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[15:53:19] [main/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com
 Whole latest.log

**Comment by SyntaxError73** [comment]
you need LLibrary 1.7.9. it says so right there... ¯\_(ツ)_/¯
