### ISSUE TITLE
Overload of gallimimus

### ISSUE THREAD

**Issue by DoveGirl777** [JurassiCraftTeam/JurassiCraft2#306]
my world keeps crashing every-time because of the overload of gallimimuses. How do I limit the amount of gallimimuses?

**Comment by DoveGirl777** [comment]
[latest.log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2128826/latest.log)

**Comment by DoveGirl777** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/22/18 2:55 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.gallimimus (org.jurassicraft.server.entity.dinosaur.GallimimusEntity)
	Entity ID: 1544
	Entity Name: Gallimimus
	Entity's Exact location: -202.73, 65.00, 234.02
	Entity's Block location: World: (-203,65,234), Chunk: (at 5,4,10 in -13,14; contains blocks -208,0,224 to -193,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.05, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: S U F F E R
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 667 Drop: 0
	Level seed: -227154463
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-174,64,92), Chunk: (at 2,4,12 in -11,5; contains blocks -176,0,80 to -161,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 66147 game time, 3205 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 936 (now: false), thunder time: 37747 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 609745400 bytes (581 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2709 Optifine OptiFine_1.12.2_HD_U_D3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                                | Signature                                |
	|:--------- |:-------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.4.2709 | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | craftstudioapi       | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| UCHIJAAAA | animania             | 1.4.7        | animania-1.12.2-1.4.8.jar             | None                                     |
	| UCHIJAAAA | waila                | 1.8.26       | Hwyla-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.14       | llibrary-1.7.14-1.12.2 .jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | jurassicraft         | 2.1.7        | JurassiCraft-1.12.2-2.1.7.jar         | None                                     |
	| UCHIJAAAA | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar  | None                                     |
	| UCHIJAAAA | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar        | None                                     |
	| UCHIJAAAA | zevac.survivalflight | 0.1.3        | Survival-Flight-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | tallgates            | 1.0.0        | TallGates-Mod-1.12.2.jar              | None                                     |
	| UCHIJAAAA | xaerominimap         | 1.15.2       | Xaeros_Minimap_1.15.2_Forge_1.12.jar  | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DoveGirl777** [comment]
thanks

**Comment by DoveGirl777** [comment]
my game crashed again

**Comment by DoveGirl777** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/24/18 4:05 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.gallimimus (org.jurassicraft.server.entity.dinosaur.GallimimusEntity)
	Entity ID: 7442
	Entity Name: Gallimimus
	Entity's Exact location: -80.61, 63.00, 190.50
	Entity's Block location: World: (-81,63,190), Chunk: (at 15,3,14 in -6,11; contains blocks -96,0,176 to -81,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.02, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Copy of Best World
	All players: 1 total; [EntityPlayerMP['DoveGirl777'/7440, l='Copy of Best World', x=72.67, y=79.50, z=145.55]]
	Chunk stats: ServerChunkCache: 1205 Drop: 0
	Level seed: -1789556842
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (83,64,208), Chunk: (at 3,4,0 in 5,13; contains blocks 80,0,208 to 95,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16086 game time, 25514 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68171 (now: false), thunder time: 118924 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 925099224 bytes (882 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2709 Optifine OptiFine_1.12.2_HD_U_D3 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State               | ID                   | Version      | Source                                | Signature                                |
	|:------------------- |:-------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAA | minecraft            | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mcp                  | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | forge                | 14.23.4.2709 | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | ColorUtility         | 1.0.4        | minecraft.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | craftstudioapi       | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| UCHIJAAAAAAAAAAAAAA | animania             | 1.4.7        | animania-1.12.2-1.4.8.jar             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | waila                | 1.8.26       | Hwyla-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | llibrary             | 1.7.14       | llibrary-1.7.14-1.12.2 .jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAAAAAAAAAAAA | jurassicraft         | 2.1.7        | JurassiCraft-1.12.2-2.1.7.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | malisiscore          | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar          | None                                     |
	| UCHIJAAAAAAAAAAAAAA | malisisdoors         | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | zevac.survivalflight | 0.1.3        | Survival-Flight-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | xaerominimap         | 1.15.2       | Xaeros_Minimap_1.15.2_Forge_1.12.jar  | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DoveGirl777'/7440, l='Copy of Best World', x=72.67, y=79.50, z=145.55]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DoveGirl777** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/24/18 4:16 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.food.FoodHelper.getHealAmount(FoodHelper.java:202)
	at org.jurassicraft.server.entity.ai.metabolism.GrazeEntityAI.func_75246_d(GrazeEntityAI.java:119)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:695)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:959)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.gallimimus (org.jurassicraft.server.entity.dinosaur.GallimimusEntity)
	Entity ID: 133
	Entity Name: Gallimimus
	Entity's Exact location: 18.61, 66.00, 269.27
	Entity's Block location: World: (18,66,269), Chunk: (at 2,4,13 in 1,16; contains blocks 16,0,256 to 31,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.05, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Best World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 635 Drop: 0
	Level seed: -1789556842
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (83,64,208), Chunk: (at 3,4,0 in 5,13; contains blocks 80,0,208 to 95,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16104 game time, 25532 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68153 (now: false), thunder time: 118906 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 503470624 bytes (480 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 6, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2709 Optifine OptiFine_1.12.2_HD_U_D3 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                                | Signature                                |
	|:--------- |:-------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.4.2709 | forge-1.12.2-14.23.4.2709.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ColorUtility         | 1.0.4        | minecraft.jar                         | None                                     |
	| UCHIJAAAA | craftstudioapi       | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| UCHIJAAAA | animania             | 1.4.7        | animania-1.12.2-1.4.8.jar             | None                                     |
	| UCHIJAAAA | waila                | 1.8.26       | Hwyla-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.14       | llibrary-1.7.14-1.12.2 .jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | jurassicraft         | 2.1.7        | JurassiCraft-1.12.2-2.1.7.jar         | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar          | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar         | None                                     |
	| UCHIJAAAA | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar  | None                                     |
	| UCHIJAAAA | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar        | None                                     |
	| UCHIJAAAA | zevac.survivalflight | 0.1.3        | Survival-Flight-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | xaerominimap         | 1.15.2       | Xaeros_Minimap_1.15.2_Forge_1.12.jar  | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
