### ISSUE TITLE
crash while velociraptor layed egg

### ISSUE THREAD

**Issue by GarchompGirl** [JurassiCraftTeam/JurassiCraft2#314]
ok so I was playing in creative mode in the latest 1.11.2 jurassicraft and I bred a velociraptor and when it layed a egg it crashed my game and heres the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PLCore (JurassiCraft-1.11.2-2.1.8.jar)
  llibrary (llibrary-1.7.10-1.11.2 (1).jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 6/25/18 2:43 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:708)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:955)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:708)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:955)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.velociraptor (org.jurassicraft.server.entity.dinosaur.VelociraptorEntity)
	Entity ID: 59400
	Entity Name: Velociraptor
	Entity's Exact location: -252.38, 42.00, 925.20
	Entity's Block location: World: (-253,42,925), Chunk: (at 3,2,13 in -16,57; contains blocks -256,0,912 to -241,255,927), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: -0.14, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: jurassic world!
	All players: 1 total; [EntityPlayerMP['GarchompGirl'/0, l='jurassic world!', x=-253.97, y=44.39, z=922.92]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: -5029598036454655020
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,50*minecraft:stone,minecraft:grass;21;village
	Level spawn location: World: (-260,4,911), Chunk: (at 12,0,15 in -17,56; contains blocks -272,0,896 to -257,255,911), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 19265 game time, 3172 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55129 (now: false), thunder time: 71252 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 382883304 bytes (365 MB) / 901066752 bytes (859 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJAAAA	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJAAAA	llibrary{1.7.10} [LLibrary] (llibrary-1.7.10-1.11.2 (1).jar) 
	UCHIJAAAA	jurassicraft{2.1.8} [JurassiCraft] (JurassiCraft-1.11.2-2.1.8.jar) 
	Loaded coremods (and transformers): 
PLCore (JurassiCraft-1.11.2-2.1.8.jar)
  org.jurassicraft.server.pl.PLTransformer
llibrary (llibrary-1.7.10-1.11.2 (1).jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['GarchompGirl'/0, l='jurassic world!', x=-253.97, y=44.39, z=922.92]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Gamebrothers4** [comment]
Not closed, Need testing

**Comment by GarchompGirl** [comment]
what does "needs verification" mean?

**Comment by Wyn-Price** [comment]
Does this happen in latest version of jc (2.1.9)

**Comment by GarchompGirl** [comment]
2.1.5

**Comment by GarchompGirl** [comment]
and no

**Comment by Wyn-Price** [comment]
Can you try on the latest version

**Comment by GarchompGirl** [comment]
i did try the latest 1.11.2 one (bc my 1.12.2 forge does not work when i try to install to launcher) and it works fine but when i used the birthing wand on my velociraptor there wasnt a egg
