### ISSUE TITLE
Crash from Herding?

### ISSUE THREAD

**Issue by DeinoRaptor** [JurassiCraftTeam/JurassiCraft2#349]
I get a crash right when I join my world
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 7/25/18 10:04 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.entity.ai.Herd.refreshMembers(Herd.java:275)
	at org.jurassicraft.server.entity.ai.Herd.update(Herd.java:233)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:872)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:962)
	at org.jurassicraft.server.entity.dinosaur.DilophosaurusEntity.func_70071_h_(DilophosaurusEntity.java:74)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.entity.ai.Herd.refreshMembers(Herd.java:275)
	at org.jurassicraft.server.entity.ai.Herd.update(Herd.java:233)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:872)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:962)
	at org.jurassicraft.server.entity.dinosaur.DilophosaurusEntity.func_70071_h_(DilophosaurusEntity.java:74)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.dilophosaurus (org.jurassicraft.server.entity.dinosaur.DilophosaurusEntity)
	Entity ID: 686
	Entity Name: Dilophosaurus
	Entity's Exact location: -1130.75, 63.00, 431.24
	Entity's Block location: World: (-1131,63,431), Chunk: (at 5,3,15 in -71,26; contains blocks -1136,0,416 to -1121,255,431), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Prehistoric Eclipse Park
	All players: 1 total; [EntityPlayerMP['bastion14'/655, l='Prehistoric Eclipse Park', x=-1023.73, y=84.54, z=423.07]]
	Chunk stats: ServerChunkCache: 742 Drop: 0
	Level seed: -1357177033474931133
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,59*minecraft:stone,3*minecraft:dirt,minecraft:grass;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (-886,4,468), Chunk: (at 10,0,4 in -56,29; contains blocks -896,0,464 to -881,255,479), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 2723633 game time, 53631 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 87404 (now: false), thunder time: 6199 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1057887992 bytes (1008 MB) / 3992977408 bytes (3808 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 Optifine OptiFine_1.12.2_HD_U_E1 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version            | Source                                            | Signature

**Comment by PT400C** [comment]
@DeinoRaptor That's actually related the this [issue](https://github.com/JurassiCraftTeam/JurassiCraft2/issues/322) about herding crashing the game.

**Comment by Shrek5InTheatres2019** [comment]
fixed in @PT400C's pull request
