### ISSUE TITLE
Client crash when joining server

### ISSUE THREAD

**Issue by celittle3** [JurassiCraftTeam/JurassiCraft2#381]
java.lang.ClassCastException: com.google.common.base.Absent cannot be cast to org.jurassicraft.server.entity.DinosaurEntity$Order
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1018)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1018)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.mussaurus (org.jurassicraft.server.entity.dinosaur.MussaurusEntity)
	Entity ID: 339
	Entity Name: Mussaurus
	Entity's Exact location: -1525.40, 66.00, 345.05
	Entity's Block location: World: (-1526,66,345), Chunk: (at 10,4,9 in -96,21; contains blocks -1536,0,336 to -1521,255,351), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Entity's Momentum: 0.00, -0.08, 0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

**Comment by PT400C** [comment]
@celittle3 Which version of the mod do you use? 1.11.2 or 1.12.2?

**Comment by celittle3** [comment]
Sorry I know better than that. 1.12.2-2.1.14  Forge 2705.  The user was trying to place an egg/dino.

**Comment by PT400C** [comment]
@celittle3 Would it be possible to you contact me via Discord? I would like to ask some further questions about that problem. My contact details: PT400C#8363

**Comment by celittle3** [comment]
ok thankyou I sent a request Celittle, When is a good time
