### ISSUE TITLE
Crash on entering helicopter

### ISSUE THREAD

**Issue by philipjholm** [JurassiCraftTeam/JurassiCraft2#409]
Hi!
I have the latest update (JurassiCraft-1.12.2-2.1.16) and I get a crash every time on multiplayer when trying to enter a placed helicopter :/

`[12:11:00] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: org/jurassicraft/server/event/KeyBindingHandler
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onEntityUpdate(HelicopterEntity.java:180) ~[HelicopterEntity.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:388) ~[vg.class:?]
	at org.jurassicraft.server.entity.vehicle.CarEntity.onUpdate(CarEntity.java:387) ~[CarEntity.class:?]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onUpdate(HelicopterEntity.java:94) ~[HelicopterEntity.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zzo000(World.java:4114) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.jurassicraft.server.event.KeyBindingHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onEntityUpdate(HelicopterEntity.java:180) ~[HelicopterEntity.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:388) ~[vg.class:?]
	at org.jurassicraft.server.entity.vehicle.CarEntity.onUpdate(CarEntity.java:387) ~[CarEntity.class:?]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onUpdate(HelicopterEntity.java:94) ~[HelicopterEntity.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zzo000(World.java:4114) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@39fa8ad2 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onEntityUpdate(HelicopterEntity.java:180) ~[HelicopterEntity.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:388) ~[vg.class:?]
	at org.jurassicraft.server.entity.vehicle.CarEntity.onUpdate(CarEntity.java:387) ~[CarEntity.class:?]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onUpdate(HelicopterEntity.java:94) ~[HelicopterEntity.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zzo000(World.java:4114) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.RuntimeException: Attempted to load class org/jurassicraft/server/event/KeyBindingHandler for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onEntityUpdate(HelicopterEntity.java:180) ~[HelicopterEntity.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:388) ~[vg.class:?]
	at org.jurassicraft.server.entity.vehicle.CarEntity.onUpdate(CarEntity.java:387) ~[CarEntity.class:?]
	at org.jurassicraft.server.entity.vehicle.HelicopterEntity.onUpdate(HelicopterEntity.java:94) ~[HelicopterEntity.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zzo000(World.java:4114) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[12:11:00] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\SevTech server\Servers\SevTechAges_308\.\crash-reports\crash-2018-08-18_12.11.00-server.txt`

**Comment by djdanby** [comment]
I have not the same issue, but problem too with helicopter. The Helicopter is bugging on the ground and can not flight.

**Comment by PT400C** [comment]
Are you on a multiplayer server or in a singleplayer world?

**Comment by djdanby** [comment]
Im on my own Multiplayer Server. I have alot Bugs with this Mod.

**Comment by PT400C** [comment]
Yeah. Just be patient and wait 👍 About LLibrary, we don't know about any problems caused by that lib. Probably those other mods cause that problem, not the lib.

**Comment by djdanby** [comment]
Ok :)

**Comment by PT400C** [comment]
@djdanby Ah, there's something you should probably know. As you use Sponge to use plugins on your server, you also added an additional cause of issues. Sponge modifies the Forge sources the mods rely on. In the most cases, this works well - but sometimes it doesn't work.

**Comment by PT400C** [comment]
With the next update, this will be resolved.
