### ISSUE TITLE
JurassiCraft startup crash with NPE

### ISSUE THREAD

**Issue by tux-in-blue** [JurassiCraftTeam/JurassiCraft2#473]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/18/18 1:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JurassiCraft (jurassicraft)
Caused by: java.lang.NullPointerException
	at org.jurassicraft.server.item.ItemHandler.init(ItemHandler.java:318)
	at org.jurassicraft.server.proxy.ServerProxy.onPreInit(ServerProxy.java:94)
	at org.jurassicraft.client.proxy.ClientProxy.onPreInit(ClientProxy.java:51)
	at org.jurassicraft.JurassiCraft.onPreInit(JurassiCraft.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 517559296 bytes (493 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                               | Signature                                |
	|:----- |:------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft     | 1.12.2       | minecraft.jar                        | None                                     |
	| UCH   | mcp           | 9.42         | minecraft.jar                        | None                                     |
	| UCH   | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | healthbar     | 1.0.7        | HealthBar-1.12-1.0.7-23.jar          | None                                     |
	| UCH   | jei           | 4.13.1.220   | jei_1.12.2-4.13.1.220.jar            | None                                     |
	| UCH   | orespawn      | 3.3.0        | OreSpawn-1.12-3.3.0.136.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | torohealthmod | 1.12.2-11    | torohealth-1.12.2-11.jar             | None                                     |
	| UCH   | xaerominimap  | 1.15.8       | Xaeros_Minimap_1.15.8_Forge_1.12.jar | None                                     |
	| UCH   | llibrary      | 1.7.14       | llibrary-1.7.14-1.12.2.jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCEE  | jurassicraft  | 2.1.18       | JurassiCraft-1.12.2-2.1.18.jar       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher

**Comment by PT400C** [comment]
Does this crash happen all the time?

**Comment by tux-in-blue** [comment]
Yes every time i try to load it up

**Comment by PT400C** [comment]
@tux-in-blue Are you on windows or MAC?

**Comment by tux-in-blue** [comment]
Mac

On Oct 19, 2018 4:06 AM, "PT400C" <notifications@github.com> wrote:

@tux-in-blue <https://github.com/tux-in-blue> Are you on windows or MAC?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JurassiCraftTeam/JurassiCraft2/issues/473#issuecomment-431280536>,
or mute the thread

**Comment by PT400C** [comment]
The next release will resolve this problem. ~Closed
