### ISSUE TITLE
Crash with SpongeForge and JurassiCraft

### ISSUE THREAD

**Issue by lichenglin19901123** [JurassiCraftTeam/JurassiCraft2#526]
I used forge-2778.sponge server

When I put Jurassic mod into the server, it will prompt level.dat to be modified. If I click ok, a lot of overworld's original items will be replaced with all sorts of weird stuff, which is very confusing.The following warning will be displayed on the server:

[11:56:41] [Server thread/ERROR] [minecraft/SaveFormatOld]: Exception reading .\world\level.dat

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:297) ~[forge-1.12.2-14.23.5.2778-universal.jar:?]

        at net.minecraftforge.registries.ForgeRegistry.loadIds(ForgeRegistry.java:695) ~[forge-1.12.2-14.23.5.2778-universal.jar:?]

        at net.minecraftforge.registries.GameData.loadFrozenDataToStagingRegistry(GameData.java:750) ~[forge-1.12.2-14.23.5.2778-universal.jar:?]

        at net.minecraftforge.registries.GameData.lambda$injectSnapshot$25(GameData.java:693) ~[forge-1.12.2-14.23.5.2778-universal.jar:?]

       at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528) ~[min

ecraft_server.1.12.2.jar:?]

        at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:690) ~[GameData.class:?]

        at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:172) ~[FMLContainer.class:?]

        at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:423) ~[FMLCommonHandler.class:?]

        at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfc.class:?] at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bcl0

00(SaveHandler.java:1068) [bfb.class:?]

        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bfb.class:?]

        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:711) [WorldManager.class:1.12.2-2768-7.1.4]

        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545) [MinecraftServer.class:?]

        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]

        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]

        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by PT400C** [comment]
~closed due to no further info given by the requester
