### ISSUE TITLE
Constant Crashes

### ISSUE THREAD

**Issue by GlossyGamer** [JurassiCraftTeam/JurassiCraft2#598]
It may be caused by the other mod I have installed, but right now it seems to be JurassiCraft itself. (At least, that's what the crash logs have said.) If there's any ways known to fix this, please let me know!

**Comment by GlossyGamer** [comment]
The problem seems to be the feeders.

**Comment by GlossyGamer** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 8/17/19 4:42 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1842)

-- Block entity being ticked --
Details:
	Name: jurassicraft:feeder // org.jurassicraft.server.block.entity.FeederBlockEntity
	Block type: ID #322 (tile.feeder // org.jurassicraft.server.block.machine.FeederBlock // jurassicraft:feeder)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (288,64,346), Chunk: (at 0,4,10 in 18,21; contains blocks 288,0,336 to 303,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #322 (tile.feeder // org.jurassicraft.server.block.machine.FeederBlock // jurassicraft:feeder)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1842)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- Affected level --
Details:
	Level name: Jurassic World Family 2.0
	All players: 1 total; [EntityPlayerMP['Glossy_Gamer'/7553, l='Jurassic World Family 2.0', x=335.78, y=63.00, z=377.79]]
	Chunk stats: ServerChunkCache: 578 Drop: 0
	Level seed: 1024752084088266932
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (193,64,279), Chunk: (at 1,4,7 in 12,17; contains blocks 192,0,272 to 207,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 263015 game time, 25912 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 933763656 bytes (890 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version      | Source                               | Signature                                |
	|:------ |:------------ |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJA | mcp          | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge        | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | radixcore    | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| LCHIJA | mca          | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar       | None                                     |
	| LCHIJA | llibrary     | 1.7.19       | llibrary-1.7.19-1.12.2.jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft | 2.1.23       | JurassiCraft-1.12.2-2.1.23.jar       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Glossy_Gamer'/7553, l='Jurassic World Family 2.0', x=335.78, y=63.00, z=377.79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GlossyGamer** [comment]
For now, I'm going to uninstal the mod. If there's a fix, please let me know here or via my discord @ Glossy_Gamer#3896

**Comment by CollingsKenny** [comment]
Hi, I believe I am also experiencing the same incident.
It seems to only happen when two or more dinosaurs are attempting to from the same feeder.
Game is currently running on a modded server.

Crash Report:
[crash-2019-09-07_22.41.34-server.txt](https://github.com/JurassiCraftTeam/JurassiCraft2/files/3587149/crash-2019-09-07_22.41.34-server.txt)
