### ISSUE TITLE
jurassicraft:entities.brachiosaurus generates game crash

### ISSUE THREAD

**Issue by Razva** [JurassiCraftTeam/JurassiCraft2#618]
Hello,

After a couple of hours the game is crashing. Here's the full log:

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/26/20 7:41 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.getSafePoint(DinosaurWalkNodeProcessor.java:120)
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.func_186320_a(DinosaurWalkNodeProcessor.java:55)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at org.jurassicraft.server.entity.ai.Family.update(Family.java:91)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:951)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1038)
	at org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity.func_70071_h_(BrachiosaurusEntity.java:28)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.getSafePoint(DinosaurWalkNodeProcessor.java:120)
	at org.jurassicraft.server.entity.ai.navigation.DinosaurWalkNodeProcessor.func_186320_a(DinosaurWalkNodeProcessor.java:55)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at org.jurassicraft.server.entity.ai.Family.update(Family.java:91)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:951)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1038)
	at org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity.func_70071_h_(BrachiosaurusEntity.java:28)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.brachiosaurus (org.jurassicraft.server.entity.dinosaur.BrachiosaurusEntity)
	Entity ID: 35
	Entity Name: Brachiosaurus
	Entity's Exact location: 798.78, 64.00, 665.44
	Entity's Block location: World: (798,64,665), Chunk: (at 14,4,9 in 49,41; contains blocks 784,0,656 to 799,255,671), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Razva'/3, l='world', x=813.85, y=64.00, z=698.11]]
	Chunk stats: ServerChunkCache: 801 Drop: 0
	Level seed: -4990607049742051197
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-224,64,68), Chunk: (at 0,4,4 in -14,4; contains blocks -224,0,64 to -209,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5749351 game time, 33976 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 67342 (now: false), thunder time: 68649 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-8-amd64
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 282697232 bytes (269 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 3 total; -XX:+UseG1GC -Xms1G -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version         | Source                                            | Signature                                |
	|:------ |:------------ |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp          | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML          | 8.0.99.99       | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCHIJA | forge        | 14.23.5.2847    | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCHIJA | worldedit    | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | llibrary     | 1.7.19          | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft | 2.1.23          | JurassiCraft-1.12.2-2.1.23.jar                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['Razva'/3, l='world', x=813.85, y=64.00, z=698.11]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)```

I guess it's because of an entity (brachiosaurus) but I can't manage to kill it.

I've tried with `/kill @e[type=entities.brachiosaurus]` but with no luck.

Thanks!

**Comment by SvenR2000** [comment]
Same problem here. A temporary solution is to teleport to the "Entity's Block location: World: (X,Y,Z)" location in the error log and kill the dinosaur. What causes the crash seems to be an infinite loop of the dinosaur losing 1 health and regenerating it every second. (Found that out with the usage of Damage Indicators Mod)
